package com.example.guessgame_cc201013

object CapitalArray {
    val words = listOf(
        "Kabul",
        "Tirana ",
        "Algiers",
        "Andorra la Vella",
        "Luanda",
        "Saint John's",
        "Buenos Aires",
        "Yerevan",
        "Canberra",
        "Vienna",
        "Baku",
        "Nassau",
        "Manama",
        "Dhaka",
        "Bridgetown",
        "Minsk",
        "Brussels",
        "Belmopan",
        "Porto Novo",
        "Thimphu",
        "La Paz",
        "Sarajevo",
        "Gaborone",
        "Brasilia",
        "Bandar Seri Begawan",
        "Sofia",
        "Ouagadougou",
        "Gitega",
        "Phnom Penh",
        "Yaounde",
        "Ottawa",
        "Praia",
        "Bangui",
        "N'Djamena",
        "Santiago",
        "Beijing",
        "Bogota",
        "Moroni",
        "Kinshasa",
        "Brazzaville",
        "San Jose",
        "Yamoussoukro",
        "Zagreb",
        "Havana",
        "Nicosia",
        "Prague",
        "Copenhagen",
        "Djibouti",
        "Roseau",
        "Santo Domingo",
        "Dili",
        "Quito",
        "Cairo",
        "San Salvador",
        "London",
        "Malabo",
        "Asmara",
        "Tallinn",
        "Mbabana",
        "Addis Ababa",
        "Palikir",
        "Suva",
        "Helsinki",
        "Paris",
        "Libreville",
        "Banjul",
        "Tbilisi",
        "Berlin",
        "Accra",
        "Athens",
        "Saint George's",
        "Guatemala",
        " Saint George",
        "Conakry",
        "Bissau",
        "Georgetown",
        "Port au Prince",
        "Tegucigalpa",
        "Budapest",
        "Reykjavik",
        "New Delhi",
        "Jakarta",
        "Tehran",
        "Baghdad",
        "Dublin",
        "Rome",
        "Kingston",
        "Tokyo",
        "Amman",
        "Nur Sultan",
        "Nairobi",
        "Tarawa Atoll",
        "Pristina",
        "Kuwait",
        "Bishkek",
        "Vientiane",
        "Riga",
        "Beirut",
        "Maseru",
        "Monrovia",
        "Tripoli",
        "Vaduz",
        "Vilnius",
        "Luxembourg",
        "Antananarivo",
        "Lilongwe",
        "Kuala Lumpur",
        "Male",
        "Bamako",
        "Valletta",
        "Majuro",
        "Nouakchott",
        "Port Louis",
        "Mexico",
        "Chisinau",
        "Monaco",
        "Ulaanbaatar",
        "Podgorica",
        "Rabat",
        "Maputo",
        "Burma",
        "Windhoek",
        "Kathmandu",
        "Amsterdam",
        "Wellington",
        "Managua",
        "Niamey",
        "Abuja",
        "Pyongyang",
        "Skopje",
        "Belfast",
        "Oslo",
        "Muscat",
        "Islamabad",
        "Melekeok",
        "Panama",
        "Port Moresby",
        "Asuncion",
        "Lima",
        "Manila",
        "Warsaw",
        "Lisbon",
        "Doha",
        "Bucharest",
        "Moscow",
        "Kigali",
        "Basseterre",
        "Castries",
        "Kingstown",
        "Apia",
        "San Marino",
        "Sao Tome",
        "Riyadh",
        "Edinburgh",
        "Dakar",
        "Belgrade",
        "Victoria",
        "Freetown",
        "Singapore",
        "Bratislava",
        "Ljubljana",
        "Honiara",
        "Mogadishu",
        "Cape Town",
        "Seoul",
        "Juba",
        "Madrid",
        "Colombo",
        "Khartoum",
        "Paramaribo",
        "Stockholm",
        "Bern",
        "Damascus",
        "Taipei",
        "Dushanbe",
        "Dodoma",
        "Bangkok",
        "Lome",
        "Nuku'alofa",
        "Port of Spain",
        "Tunis",
        "Ankara",
        "Ashgabat",
        "Funafuti",
        "Kampala",
        "Kiev",
        "Abu Dhabi",
        "London",
        "Washington",
        "Montevideo",
        "Tashkent",
        "Port Vila",
        "Vatican",
        "Caracas",
        "Hanoi",
        "Cardiff",
        "Sana'a",
        "Lusaka",
        "Harare"

    )
}

